### ISSUE TITLE
Fill the tables

### ISSUE THREAD

**Issue by jobarratt** [okfn/data-tables.csv#11]
# Description

Make sure the tables are filled! Ensure that people attending the csv,conf,v3 are aware about Data Tables and understand how to participate.

# Tasks

- [x] Confirm details with organising committee
- [x] Write blog post promoting the data tables for labs and to be cross posted by others
- [x] Promote event
  - [x] Email attendees in advance of event with link to blog post
  - [x] Slack message with link to blog post
  - [x] Tweet it, yo, with link to blog post
- [ ] Announcement at the welcoming session of the conference
- [ ] Ensure information is easily accessible to conference attendees on the event. Do we need signs/posters?

**Comment by danfowler** [comment]
@jobarratt I don't think it belongs on the Labs blog.

**Comment by pwalsh** [comment]
csv,conf,v3 is over!
