### ISSUE TITLE
wrap up

### ISSUE THREAD

**Issue by jobarratt** [okfn/data-tables.csv#12]
# Tasks

- [x] Make sure we have a way of capturing outputs from the event
  - [x] e.g. everybody works on Jupyter Notebooks
- [ ] Write and share Blog post summarising the event
- [ ] Make sure participants are aware of the overall outcomes of the data tables and know how to find out more about the themes, projects and subjects covered.
