### ISSUE TITLE
Prepare Data Theme: Fiscal Data

### ISSUE THREAD

**Issue by pwalsh** [okfn/data-tables.csv#5]
# Description

Prepare some material that participants can dive into.

The output should be that we have a nice set of materials for exploring a data themes, and some particular ideas that people could work towards if they want.

# Tasks

- [ ] Identify core and interesting datasets that can be wrangled
  - [ ] Prepare a document/list of them
- [ ] Identify core and interesting things that can be done with this data
  - [ ] Prepare a document/list of them
- [ ] Identify possible contextual datasets that can be used with this data
  - [ ] Prepare a document/list of them
- [ ] Identify open source platforms and tools that already are designed around this data (e.g.: OpenSpending)
  - [ ] Prepare a document/list of them

**Comment by danfowler** [comment]
Given that the conference is based in the US, @annafralberts suggested we use the newly released http://usafacts.org/ database.  Looking through it, we noticed that the sources are not directly linked and that it might be an interested exercise to crowdsource the links to the public data sources: https://www.usafacts.org/sources

(@annafralberts 👨🏽‍⚕️)

https://discuss.okfn.org/t/steve-ballmer-serves-up-a-fascinating-data-trove/5091

**Comment by morchickit** [comment]
You might want to speak to these guys about data, they are planning a hackathon next week on US Spending data - http://eventmanagement.cvent.com/events/data-act-hackathon/event-summary-b83e69c2b10c4fce91229053a2ce086d.aspx

**Comment by morchickit** [comment]
You might also want to check this: https://www.usaspending.gov/Pages/Default.aspx (I think US Facts is a lot of hype ATM)

**Comment by danfowler** [comment]
@morchickit excellent suggestion!

**Comment by danfowler** [comment]
http://subsidystories.eu/

**Comment by pwalsh** [comment]
csv,conf,v3 is over!
