### ISSUE TITLE
Prepare Data Theme: Agricultural data

### ISSUE THREAD

**Issue by pwalsh** [okfn/data-tables.csv#6]
# Description

Prepare some material that participants can dive into.

The output should be that we have a nice set of materials for exploring a data themes, and some particular ideas that people could work towards if they want.

# Tasks

- [ ] Identify core and interesting datasets that can be wrangled
  - [ ] Prepare a document/list of them
- [ ] Identify core and interesting things that can be done with this data
  - [ ] Prepare a document/list of them
- [ ] Identify possible contextual datasets that can be used with this data
  - [ ] Prepare a document/list of them
- [ ] Identify open source platforms and tools that already are designed around this data
  - [ ] Prepare a document/list of them

**Comment by danfowler** [comment]
@jobarratt based on some feedback from our person at GODAN, I made a start.  Given "farmerama", do you have any suggestions of interesting things to do with these types of datasets?

https://github.com/csvconf/data-tables.csv/blob/master/themes/agricultural-data.md

I also thought it might be useful to make this as local, so I started with a Oregon provider of agricultural data.

**Comment by pwalsh** [comment]
csv,conf,v3 is over!
