### ISSUE TITLE
Prepare data theme: Cultural Heritage data

### ISSUE THREAD

**Issue by pwalsh** [okfn/data-tables.csv#7]
# Description

Prepare some material that participants can dive into.

The output should be that we have a nice set of materials for exploring a data themes, and some particular ideas that people could work towards if they want.

# Tasks

- [x] Identify core and interesting datasets that can be wrangled
  - [x] Prepare a document/list of them
- [x] Identify core and interesting things that can be done with this data
  - [x] Prepare a document/list of them
- [x] Identify possible contextual datasets that can be used with this data
  - [x] Prepare a document/list of them
- [x] Identify open source platforms and tools that already are designed around this data
  - [x] Prepare a document/list of them

**Comment by danfowler** [comment]
Dropping this here for inspiration.  It is a FiveThirtyEight piece that takes the recently released Metropolitan Museum of Art dataset and pulls out some interesting insights:

http://fivethirtyeight.com/features/an-excavation-of-one-of-the-worlds-greatest-art-collections/

Lots of stuff about vases 🏺⚱️🏺

**Comment by thomasgpadilla** [comment]
This is awesome! One small suggestion, maybe re-title the theme  "cultural heritage data"? Or "museum, library, and archive data"? Bigger bucket might pull more folks and encourage cross institutional collaboration.

**Comment by danfowler** [comment]
@thomasgpadilla yes, I was thinking the same!

**Comment by danfowler** [comment]
Also this: https://creativecommons.org/2017/04/20/europeana-search/

**Comment by thomasgpadilla** [comment]
a couple of more examples:

National Library of the Netherlands
https://www.kb.nl/bronnen-zoekwijzers/dataservices-en-apis

University of Pennsylvania
http://openn.library.upenn.edu/

British Library
http://www.bl.uk/collection-guides/datasets-for-content-mining
http://www.bl.uk/collection-guides/datasets-for-image-analysis

Tate Modern
https://github.com/tategallery/collection

University of Miami
https://github.com/UMiamiLibraries/collections-as-data

**Comment by danfowler** [comment]
👍
