### ISSUE TITLE
Prepare data theme: Endangered US Open Data

### ISSUE THREAD

**Issue by pwalsh** [okfn/data-tables.csv#8]
# Description

Prepare some material that participants can dive into.

The output should be that we have a nice set of materials for exploring a data themes, and some particular ideas that people could work towards if they want.

# Tasks

- [ ] Identify core and interesting datasets that can be wrangled
  - [ ] Prepare a document/list of them
- [ ] Identify core and interesting things that can be done with this data
  - [ ] Prepare a document/list of them
- [ ] Identify possible contextual datasets that can be used with this data
  - [ ] Prepare a document/list of them
- [ ] Identify open source platforms and tools that already are designed around this data
  - [ ] Prepare a document/list of them

**Comment by pwalsh** [comment]
@jobarratt can you follow this up with Max, and we see if we keep it (and ask him to prep some materials) or if we remove it (because he is already doing something like this after csv conf)

**Comment by pwalsh** [comment]
csv,conf,v3 is over!
