### ISSUE TITLE
"Schedule" and co-ordination

### ISSUE THREAD

**Issue by pwalsh** [okfn/data-tables.csv#9]
# Description

Have everything in place for this to run smoothly, casually, and informally in parallel to the conference speaking stream.

# Tasks

- [x] Ensure the arrangement of the space is good. 
- [x] Check and the general scheduling.
- [x] Always 1-2 people from OKI around?
- [x] Move this repository to the csvconf organisation on GitHub?

**Comment by danfowler** [comment]
Hi all, this is what I have come up with for scheduling tomorrow.  Let me know if this is unworkable.  I am still waiting for some feedback on the late afternoon sessions.  @joehand did you want to book a particular time to work on Dat stuff?

## Day 1

Time | Facilitator | Session
---- | ------------ | -----
10:30a-12p | @bmpvieira | **Bionode** How Bionode uses Node.JS Streams to process big genomic data http://www.bionode.io/
1:30p-3p | @nokome | **Stencila** A hands-on introduction to accessible, reproducible data analysis using Stencila: learn how to create interactive, data-driven documents using your choice of (or a mix of) Javascript, Python, R, SQL or Mini (a very simple, embedded, purely-functional language). Bring your own data! https://stenci.la/
3:30p-4:30p | @datadotworld | **data.world** Uploading datasets to data.world https://data.world/

## Day 2

Time | Facilitator | Session
---- | ------------ | ----
11a-12:30p | @akariv | **Data Package Pipelines** An exploration of the messy world of ETLing public data, and a suite of tools designed expressly for the unique challenges therein. https://github.com/frictionlessdata/datapackage-pipelines
1p-3p |  @jasoncrawford | **Fieldbook** Fieldbook is a information tool which combines the best of a database and a spreadsheet. Like a spreadsheet, it has a simple, lightweight grid UI; like a database, it supports relational modeling and querying. Also, every book gets an automatic JSON-based REST API. https://fieldbook.com/
3:30p-4:30p | (@joehand TBD) | **Dat** Using Dat to Distribute Data Packages https://datproject.org/

**Comment by nokome** [comment]
Good for me, thanks!

**Comment by bmpvieira** [comment]
Me too, thanks!

Bruno

**Comment by joehand** [comment]
I should be able to facilitate for the late afternoon session tomorrow.

**Comment by danfowler** [comment]
Hi sorry @joehand this slot was taken.  I have scheduled you for the next day, but we can discuss! 

Also, late afternoon times were shifted a bit by a change to the general schedule.  Ordering remains the same.
